### ISSUE TITLE
gathertweet not running as cron job

### ISSUE THREAD

**Issue by latlio** [gadenbuie/gathertweet#7]
Hi Garrick,

Thanks so much for writing `gathertweet`! I've been able to use it directly with the command line and it works great! However, when I try to schedule it as a cron job using the command you supply in the readme (0 0 * * * (cd ~/my-folder && ~/bin/gathertweet search --polite 'rstats' >> gathertweet.log), I see that the `gathertweet.log` file is created, but it's empty)

I've confirmed that gathertweet is located in my usr/local/bin/ directory, and I've ensured that it's executable.

Any clues as to what might be the underlying problem? What other information can I supply to help you help me?

Lathan

**Comment by gadenbuie** [comment]
Hmmm I'm not really sure, but you should try to check the cron logs directly. Here's an example article that might be helpful: https://linuxhint.com/check-cron-logs-linux/

I haven't been doing much with rtweet, but I just updated an app this weekend and realized that there's quite a lot that has changed recently. If gathertweet still works now, it's very possible it won't work well very soon, so at the very least you'll probably want to keep track of which version of rtweet is working for you.

**Comment by latlio** [comment]
Thanks Garrick. Yea definitely weird, I've tried checking the cron logs directly, and it's empty as well. Good to know though that rtweet has changed a lot so I may consider updating the code to fit the newest version of tweet
